export const currencies = [
  { code: "USD", name: "US Dollar", flag: "🇺🇸" },
  { code: "EUR", name: "Euro", flag: "🇪🇺" },
  { code: "GBP", name: "British Pound", flag: "🇬🇧" },
  { code: "JPY", name: "Japanese Yen", flag: "🇯🇵" },
  { code: "CHF", name: "Swiss Franc", flag: "🇨🇭" },
  { code: "AUD", name: "Australian Dollar", flag: "🇦🇺" },
  { code: "CAD", name: "Canadian Dollar", flag: "🇨🇦" },
  { code: "NZD", name: "New Zealand Dollar", flag: "🇳🇿" },
  { code: "CNY", name: "Chinese Yuan", flag: "🇨🇳" },
  { code: "HKD", name: "Hong Kong Dollar", flag: "🇭🇰" },
  { code: "SGD", name: "Singapore Dollar", flag: "🇸🇬" },
  { code: "INR", name: "Indian Rupee", flag: "🇮🇳" },
  { code: "AED", name: "UAE Dirham", flag: "🇦🇪" },
  { code: "SAR", name: "Saudi Riyal", flag: "🇸🇦" },
  { code: "QAR", name: "Qatari Riyal", flag: "🇶🇦" },
  { code: "ZAR", name: "South African Rand", flag: "🇿🇦" },
  { code: "SEK", name: "Swedish Krona", flag: "🇸🇪" },
  { code: "NOK", name: "Norwegian Krone", flag: "🇳🇴" },
  { code: "DKK", name: "Danish Krone", flag: "🇩🇰" },
  { code: "PLN", name: "Polish Zloty", flag: "🇵🇱" },
  { code: "CZK", name: "Czech Koruna", flag: "🇨🇿" },
  { code: "HUF", name: "Hungarian Forint", flag: "🇭🇺" },
  { code: "RON", name: "Romanian Leu", flag: "🇷🇴" },
  { code: "TRY", name: "Turkish Lira", flag: "🇹🇷" },
  { code: "MXN", name: "Mexican Peso", flag: "🇲🇽" },
  { code: "BRL", name: "Brazilian Real", flag: "🇧🇷" },
  { code: "ARS", name: "Argentine Peso", flag: "🇦🇷" },
  { code: "CLP", name: "Chilean Peso", flag: "🇨🇱" },
  { code: "COP", name: "Colombian Peso", flag: "🇨🇴" },
  { code: "PEN", name: "Peruvian Sol", flag: "🇵🇪" },
  { code: "KRW", name: "South Korean Won", flag: "🇰🇷" },
  { code: "THB", name: "Thai Baht", flag: "🇹🇭" },
  { code: "MYR", name: "Malaysian Ringgit", flag: "🇲🇾" },
  { code: "IDR", name: "Indonesian Rupiah", flag: "🇮🇩" },
  { code: "PHP", name: "Philippine Peso", flag: "🇵🇭" },
  { code: "VND", name: "Vietnamese Dong", flag: "🇻🇳" },
  { code: "PKR", name: "Pakistani Rupee", flag: "🇵🇰" },
  { code: "EGP", name: "Egyptian Pound", flag: "🇪🇬" },
  { code: "NGN", name: "Nigerian Naira", flag: "🇳🇬" },
  { code: "KES", name: "Kenyan Shilling", flag: "🇰🇪" },
  { code: "GHS", name: "Ghanaian Cedi", flag: "🇬🇭" },
  { code: "MAD", name: "Moroccan Dirham", flag: "🇲🇦" },
  { code: "TWD", name: "Taiwan Dollar", flag: "🇹🇼" },
  { code: "BDT", name: "Bangladeshi Taka", flag: "🇧🇩" },
  { code: "LKR", name: "Sri Lankan Rupee", flag: "🇱🇰" },
  { code: "ISK", name: "Icelandic Krona", flag: "🇮🇸" },
  { code: "JOD", name: "Jordanian Dinar", flag: "🇯🇴" },
  { code: "KWD", name: "Kuwaiti Dinar", flag: "🇰🇼" },
  { code: "BHD", name: "Bahraini Dinar", flag: "🇧🇭" },
  { code: "OMR", name: "Omani Rial", flag: "🇴🇲" },
  { code: "UYU", name: "Uruguayan Peso", flag: "🇺🇾" },
  { code: "DOP", name: "Dominican Peso", flag: "🇩🇴" },
  { code: "JMD", name: "Jamaican Dollar", flag: "🇯🇲" },
  { code: "XOF", name: "West African CFA Franc", flag: "🌍" },
  { code: "XAF", name: "Central African CFA Franc", flag: "🌍" },
  { code: "XPF", name: "CFP Franc", flag: "🌴" },
  { code: "BWP", name: "Botswana Pula", flag: "🇧🇼" },
  { code: "TZS", name: "Tanzanian Shilling", flag: "🇹🇿" },
  { code: "UGX", name: "Ugandan Shilling", flag: "🇺🇬" },
  { code: "MUR", name: "Mauritian Rupee", flag: "🇲🇺" },
  { code: "FJD", name: "Fijian Dollar", flag: "🇫🇯" },
  { code: "PGK", name: "Papua New Guinea Kina", flag: "🇵🇬" },
  { code: "NPR", name: "Nepalese Rupee", flag: "🇳🇵" },
  { code: "LAK", name: "Laotian Kip", flag: "🇱🇦" },
  { code: "KHR", name: "Cambodian Riel", flag: "🇰🇭" },
  { code: "MMK", name: "Myanmar Kyat", flag: "🇲🇲" },
  { code: "MNT", name: "Mongolian Tugrik", flag: "🇲🇳" },
  { code: "KZT", name: "Kazakhstani Tenge", flag: "🇰🇿" },
  { code: "UZS", name: "Uzbekistani Som", flag: "🇺🇿" },
  { code: "AZN", name: "Azerbaijani Manat", flag: "🇦🇿" },
  { code: "AMD", name: "Armenian Dram", flag: "🇦🇲" },
  { code: "GEL", name: "Georgian Lari", flag: "🇬🇪" },
  { code: "MDL", name: "Moldovan Leu", flag: "🇲🇩" },
  { code: "KGS", name: "Kyrgyzstani Som", flag: "🇰🇬" },
  { code: "TJS", name: "Tajikistani Somoni", flag: "🇹🇯" },
  { code: "IRR", name: "Iranian Rial", flag: "🇮🇷" },
  { code: "IQD", name: "Iraqi Dinar", flag: "🇮🇶" },
  { code: "LBP", name: "Lebanese Pound", flag: "🇱🇧" },
  { code: "SYP", name: "Syrian Pound", flag: "🇸🇾" },
  { code: "AFN", name: "Afghan Afghani", flag: "🇦🇫" },
  { code: "ETB", name: "Ethiopian Birr", flag: "🇪🇹" },
  { code: "SDG", name: "Sudanese Pound", flag: "🇸🇩" },
  { code: "RSD", name: "Serbian Dinar", flag: "🇷🇸" },
  { code: "BAM", name: "Bosnia Convertible Mark", flag: "🇧🇦" },
  { code: "MKD", name: "Macedonian Denar", flag: "🇲🇰" },
  { code: "HRK", name: "Croatian Kuna*", flag: "🇭🇷" },
];
